global:
  scrape_interval: 10s

rule_files:
  - "/etc/prometheus/alert-rule.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'Bizzabo-server'
    static_configs:
      - targets: ['bizzabo:9999']
