apiVersion: apps/v1
kind: Deployment
metadata:
  name: bizzabo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bizzabo-app
  template:
    metadata:
      labels:
        app: bizzabo-app
    spec:
      containers:
      - name: bizzabo-app
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        image: bizzabo-app
        ports:
        - containerPort: 9999
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: bizzabo-app-service
spec:
  selector:
    app: bizzabo-app
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  type: NodePort
