apiVersion: apps/v1
kind: Deployment
metadata:
  name: bizzabo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bizzabo-app
  template:
    metadata:
      labels:
        app: bizzabo-app
    spec:
      containers:
      - name: bizzabo-app
        image: bizzabo-app
        ports:
        - containerPort: 9999
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: bizzabo-app-service
spec:
  selector:
    app: bizzabo-app
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  # This will need to change in production to load balancer (or better yet, an Ingress)
  type: NodePort
