apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: provisioning-volume
          mountPath: /etc/grafana/provisioning
        - name: dashboards-volume
          mountPath: /var/lib/grafana/dashboards
      volumes:
      - name: provisioning-volume
        #This will need to change in production to persistent volume claim, when using locally change the absolute path for the files
        hostPath:
          path: /projects/BizzaboAssignment/grafana/provisioning
      - name: dashboards-volume
        hostPath:
          path: /projcets/BizzaboAssignment/grafana/dashboards

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
  #This will need to change in production to load balancer
  type: NodePort
