apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  alert-rule.yml: |
    groups:
    - name: bizzabo_alert_rules
      rules:
      - alert: HighHTTPErrorRate
        expr: http_non_200_responses_last_minute  > 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: High HTTP error rate detected
          description: 'There have been more than 1 errors in the last minute'
  prometheus.yml: |
    global:
      scrape_interval: 10s

    rule_files:
      - "/etc/prometheus/alert-rule.yml"

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093

    scrape_configs:
      - job_name: 'Bizzabo-server'
        static_configs:
          - targets: ['bizzabo-app-service:9999']
